# Generated by Django 5.0 on 2023-12-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_learnerclass_description_classunit_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classunit',
            name='description',
            field=models.TextField(blank=True, default='Key 7 or class 9E', null=True),
        ),
    ]
