# Generated by Django 5.0 on 2024-01-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_classunit_teacher_classunit_user_teacher_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
