# Generated by Django 5.0 on 2024-01-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_learner_reg_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerclass',
            name='lesson_no',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
